core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('', include('account.urls')),
    path('quiz/', include('quiz.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
               static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.urls import path

from quiz.views import quiz_categories, quiz_by_slug

app_name = 'quiz'

urlpatterns = [
    path('', quiz_categories, name='quiz-categories'),
    path('<slug:slug>', quiz_by_slug, name='categories-slug'),
]

quiz/models.py
from django.db import models
from django.utils.text import slugify


class Category(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='quiz-images/', null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.id} - {self.title}'


class Question(models.Model):
    category = models.ForeignKey(Category, related_name='category', on_delete=models.CASCADE)
    question = models.CharField(max_length=255)
    marks = models.IntegerField(default=5)

    def __str__(self):
        return f'{self.id} - {self.question}'


class Answer(models.Model):
    question = models.ForeignKey(Question, related_name='question_answer', on_delete=models.CASCADE)
    answer = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.id} - {self.answer}'

quiz/views.py
from random import shuffle, sample

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from quiz.models import Answer, Question, Category


def quiz_categories(request):
    categories = Category.objects.all()
    context = {
        "categories": categories,
    }
    return render(request, 'quiz/categories_list.html', context=context)


def quiz_by_slug(request, slug):
    quiz_questions = Question.objects.filter(category__slug=slug)
    answers = Answer.objects.filter(question__in=quiz_questions)
    correct_answer = {}
    for i in answers:
        if i.is_correct:
            correct_answer[i.question.id] = i.id
    answers = list(answers)
    answers = sample(answers, len(answers))

    if request.method == 'POST':
        selected_answer = request.POST.dict()
        selected_answer.pop('csrfmiddlewaretoken')
        if len(selected_answer) == len(correct_answer):
            selected_answer = list(selected_answer.values())
            correct_answer = list(correct_answer.values())
            temp = False
            for i in range(0, len(selected_answer)):
                if int(selected_answer[i]) == correct_answer[i]:
                    temp = True
                else:
                    temp = False
            if temp:
                return render(request, 'quiz/congratulations.html')
        return render(request, 'quiz/failed.html')
    context = {
        'quiz_questions': quiz_questions,
        'answers': answers,
        'category_slug': slug,
    }
    return render(request, 'quiz/quiz_by_slug.html', context)

templates/quiz/categories_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Quiz
{% endblock  %}

{% block content %}

<div class="container">
    <br>
    <div class="row">
        {% for category in categories %}
        <div class="col-md-4 mb-4">
            <a href="{% url 'quiz:categories-slug' slug=category.slug %}" style="text-decoration: none;">
                <div class="card">
                    <img src="{{category.image.url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{category.title}}</h5>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/quiz/congratulations.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home page{% endblock %}
{% block content %}

{% include 'navbar.html' %}
<br>
<h1>Congratulation</h1>
<p>If you want to try again, please return to home page</p>
{% endblock %}

templates/quiz/failed.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home page{% endblock %}
{% block content %}

{% include 'navbar.html' %}
<br>
<h1>Failed</h1>
<p>If you want to try again, please return to home page</p>
{% endblock %}

templates/quiz/quiz_by_slug.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Quiz
{% endblock  %}

{% block content %}

<form method="post" action="{% url 'quiz:categories-slug' slug=category_slug %}">
    {% csrf_token %}

    {% for quiz in quiz_questions %}
    <p>{{ quiz.question }}</p>
    {% for answer in answers %}
    {% if answer.question == quiz %}
    <input type="radio" id="{{ answer.id }}" name="{{ quiz.id }}" value="{{ answer.id }}">
    <label for="{{ answer.id }}">{{ answer.answer }}</label><br>
    {% endif %}
    {% endfor %}
    <p>_____________________________________________________</p>
    {% endfor %}

    <input type="submit" value="Submit">
</form>

{% endblock %}